services:
  db:
    #Container name
    container_name: db 

    #Build context 
    build:
      context: ./db
      dockerfile: Dockerfile

    #Set restart to always
    restart: always

    # Share container db-pgadmin with pgadmin
    networks:
      - postgre-pgadmin


    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

    #Mount volume postgresql-data to directory at the /bitnami/postgresql path
    volumes:
      - postgresql-data:/bitnami/postgresql
      - ./db/star_schema_1/create_schema_script.sql:/workspace/star_schema_1/create_schema_script.sql
      - ./db/star_schema_2/create_schema_script.sql:/workspace/star_schema_2/create_schema_script.sql
  db-pgadmin:
    #Container name
    container_name: db-pgadmin 

    #Build image
    image: dpage/pgadmin4

    #Set restart to always
    restart: always

    #Depend on service db
    depends_on:
      - db

    #Share container network db-pgadmin with db
    networks:
      - postgre-pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin

    #Forward port 8888 from localhost to port 80 in container
    ports:
      - "8888:80"
    
    #Mount volume pgadmin-data to directory at the /var/lib/pgadmin path
    volumes:
      - pgadmin-data:/var/lib/pgadmin

    
  

networks:
  postgre-pgadmin:
    driver: bridge

volumes:
  pgadmin-data:
    driver: local
  postgresql-data:
    driver: local
